# Site settings
title: "Yohannes W. Shewalul"
description: "A resume for Yohannes W. Shewalul."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yohannes W. Shewalul"
resume_title:                   "PhD Candidate in Structural Fire Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yshewalul@sun.ac.za"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+27727065780"
resume_contact_address:         "Stellenbosch, South Africa"

resume_header_contact_info:     "Stellenbosch • +27727065780 • yshewalul@sun.ac.za"
display_header_contact_info:    "true"

resume_header_intro: "<p>Dedicated and results-oriented PhD candidate in Structural Fire Engineering. SFPE Foundation Student
Research Grant 2021 recipient. Expertise in interdisciplinary knowledge in fire safety engineering, structural
fire engineering, material characterization, and sustainable construction practices. Proficient in code
compliance (NFPA) and advanced CFD fire, drafting, and thermo-mechanical modelling tools. Skilled in fire
dynamics, performance-based design, and fire risk analysis, with excellent problem-solving and
communication skills. Ready to contribute to innovative fire protection solutions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_publications:    true
resume_section_conferences:     true
resume_section_interests:       true
resume_section_recognition:     true
resume_section_projects:        true
resume_section_teaching:        true
resume_section_experience:      true
resume_section_skills:          true
resume_section_associations:    true
resume_section_presentations:   true
resume_section_links:           true
resume_section_references:      true


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/yshewalul/portfolio/"
  resume_twitter_url:           "http://twitter.com/yohannes_ws"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yshewalul/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
